---
kind: pipeline
type: docker
name: gcc_build

steps:
  - name: lint
    image: vesoft/nebula-dev:latest
    commands:
      - cd .linters/cpp && ln -snf hooks/pre-commit.sh
      - ./pre-commit.sh $(git --no-pager diff --name-only $(git log --oneline -n 1 | cut -d ' ' -f 1,5) | sed -E 's/(.*)/..\/..\/\1/g')

  - name: prepare
    image: vesoft/nebula-dev:latest
    commands:
      - mkdir -p ~/.ssh
      - cp ./ci/deploy_key ~/.ssh/id_rsa
      - chmod 0400 ~/.ssh/id_rsa
      - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  - name: gcc_build
    image: vesoft/nebula-dev:latest
    commands:
      - cmake -E make_directory build
      - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=on -B build/
      - cmake --build build/ -j $(nproc)
      - ctest -j $(nproc) --timeout 400 --output-on-failure
    depends_on:
      - lint

---
kind: pipeline
type: docker
name: clang_build

steps:
  - name: lint
    image: vesoft/nebula-dev:latest
    commands:
      - cd .linters/cpp && ln -snf hooks/pre-commit.sh
      - ./pre-commit.sh $(git --no-pager diff --name-only $(git log --oneline -n 1 | cut -d ' ' -f 1,5) | sed -E 's/(.*)/..\/..\/\1/g')

  - name: prepare
    image: vesoft/nebula-dev:latest
    commands:
      - mkdir -p ~/.ssh
      - cp ./ci/deploy_key ~/.ssh/id_rsa
      - chmod 0400 ~/.ssh/id_rsa
      - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  - name: clang_build
    image: vesoft/nebula-dev:latest
    commands:
      - cmake -E make_directory build
      - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=on -DENABLE_UBSAN=on -DENABLE_TESTING=on -B build/
      - cmake --build build/ -j $(nproc)
      - ctest -j $(nproc) --timeout 400 --output-on-failure
    depends_on:
      - lint
