---
kind: pipeline
type: docker
name: gcc_build

steps:
  - name: lint
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - ln -snf $PWD/.linters/cpp/hooks/pre-commit.sh $PWD/.linters/cpp/pre-commit.sh
      - .linters/cpp/pre-commit.sh $(git --no-pager diff --diff-filter=d --name-only HEAD^ HEAD)

  - name: gcc_build
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - ./ci/deploy.sh
      - mkdir build && cd build
      - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=on ..
      - make -j $(nproc)
      - ctest -j $(nproc) --timeout 400 --output-on-failure
    depends_on:
      - lint

---
kind: pipeline
type: docker
name: clang_build

steps:
  - name: lint
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - ln -snf $PWD/.linters/cpp/hooks/pre-commit.sh $PWD/.linters/cpp/pre-commit.sh
      - .linters/cpp/pre-commit.sh $(git --no-pager diff --diff-filter=d --name-only HEAD^ HEAD)

  - name: clang_build
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - ./ci/deploy.sh
      - mkdir build && cd build
      - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=on -DENABLE_TESTING=on ..
      - make -j $(nproc)
      - ctest -j $(nproc) --timeout 400 --output-on-failure
    depends_on:
      - lint
