---
kind: pipeline
type: docker
name: gcc_build

steps:
  - name: lint
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - ln -snf $PWD/.linters/cpp/hooks/pre-commit.sh $PWD/.linters/cpp/pre-commit.sh
      - .linters/cpp/pre-commit.sh $(git --no-pager diff --diff-filter=d --name-only HEAD^ HEAD)

  - name: gcc_build
    pull: always
    image: vesoft/nebula-dev:ubuntu1804
    environment:
      NEBULA_STORAGE_REPO_URL:
        from_secret: NEBULA_STORAGE_REPO_URL
    commands:
      - ./ci/deploy.sh
      - /usr/bin/pip3 install -r tests/requirements.txt
      - mkdir build && cd build
      - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=on -DNEBULA_STORAGE_REPO_URL=$NEBULA_STORAGE_REPO_URL ..
      - make -j $(nproc)
      - ctest -j $(nproc) --timeout 400 --output-on-failure
      - cd tests && ./ntr -h
    depends_on:
      - lint

---
kind: pipeline
type: docker
name: clang_build

steps:
  - name: lint
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - ln -snf $PWD/.linters/cpp/hooks/pre-commit.sh $PWD/.linters/cpp/pre-commit.sh
      - .linters/cpp/pre-commit.sh $(git --no-pager diff --diff-filter=d --name-only HEAD^ HEAD)

  - name: clang_build
    pull: always
    image: vesoft/nebula-dev:ubuntu1804
    environment:
      NEBULA_STORAGE_REPO_URL:
        from_secret: NEBULA_STORAGE_REPO_URL
    commands:
      - ./ci/deploy.sh
      - /usr/bin/pip3 install -r tests/requirements.txt
      - mkdir build && cd build
      - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=on -DENABLE_TESTING=on -DNEBULA_STORAGE_REPO_URL=$NEBULA_STORAGE_REPO_URL ..
      - make -j $(nproc)
      - ctest -j $(nproc) --timeout 400 --output-on-failure
      - cd tests && ./ntr -h
    depends_on:
      - lint
