---
kind: pipeline
type: docker
name: gcc_build

steps:
  - name: lint
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - ./ci/test.sh lint

  - name: gcc_build
    pull: always
    image: vesoft/nebula-dev:ubuntu1804
    environment:
      NEBULA_TEST_LOGS_DIR: /tmp/nebula-ci-logs
      NEBULA_STORAGE_REPO_URL:
        from_secret: NEBULA_STORAGE_REPO_URL
    commands:
      - ./ci/test.sh
    depends_on:
      - lint

---
kind: pipeline
type: docker
name: clang_build

steps:
  - name: lint
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - ./ci/test.sh lint

  - name: clang_build
    pull: always
    image: vesoft/nebula-dev:ubuntu1804
    environment:
      NEBULA_TEST_LOGS_DIR: /tmp/nebula-ci-logs
      NEBULA_STORAGE_REPO_URL:
        from_secret: NEBULA_STORAGE_REPO_URL
    commands:
      - ./ci/test.sh prepare
      - ./ci/test.sh clang
      - ./ci/test.sh test
    depends_on:
      - lint
