name: 'Extract tag name'
description: 'Extract tag name'
outputs:
  tag:
    description: 'tag name'
runs:
  using: "composite"
  steps:
    - run: |
        tag=$(echo ${{ github.ref }} | rev | cut -d/ -f1 | rev)
        echo "::set-output name=tag::$tag"
      shell: bash
