apiVersion: batch/v1
kind: Job
metadata:
  name: nebula-test
spec:
  template:
    metadata:
      name: nebula-test
    spec:
      restartPolicy: Never
      containers:
        - name: nebula-test
          image: vesoft/nebula-dev:centos7
          command: ["bash", "-c"]
          args:
            - "git clone --single-branch -b master https://github.com/vesoft-inc/nebula-graph && ./nebula-graph/ci/test.sh k8s"
