name: cluster

on:
  schedule:
    - cron: '0 20 * * *'

defaults:
  run:
    shell: bash

jobs:
  k8s:
    name: k8s
    runs-on: [self-hosted, k8s-master]
    steps:
      - uses: actions/checkout@v2
      - name: Upgrade and test in cluster
        run: sudo ./ci/test-k8s-cluster.sh
