name: docker

on:
  push:
    branches:
      - 'v[0-9]+.*'
  schedule:
    - cron: '0 18 * * *'

jobs:
  docker:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: tag
        run: |
          TAG=${{ github.event_name == 'push' }} && $(echo "${{ github.ref }}" | tr / ' ' | cut -d ' ' -f 3) || echo "v2-nightly"
          echo "::set-output name=TAG::$TAG"
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vesoft/nebula-graphd
          tags: ${{ steps.tag.outputs.TAG }}
          cache_froms: vesoft/nebula-dev:centos7
          add_git_labels: true
