name: pull_request

on:
  pull_request:
    types: [synchronize, reopened, labeled]
    branches:
      - master
      - 'v[0-9]+.*'

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: lint
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ready-for-testing') }}
    runs-on: ubuntu-latest
    outputs:
      has_source_files: ${{ steps.filter-source-files.outputs.has_source_files }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Cpplint
        run: |
          ln -snf $PWD/.linters/cpp/hooks/pre-commit.sh $PWD/.linters/cpp/pre-commit.sh
          .linters/cpp/pre-commit.sh $(git --no-pager diff --diff-filter=d --name-only HEAD^ HEAD)
      - name: Pylint
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          DEFAULT_WORKSPACE: ${{ github.workspace }}/tests
          PYTHON_PYLINT_CONFIG_FILE: ${{ github.workspace }}/tests/.pylintrc
          VALIDATE_PYTHON_FLAKE8: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Filter source files
        id: filter-source-files
        run: |
          diff_commits=$(git log --oneline -n 1 | cut -d' ' -f1,5)
          source_files=$(git --no-pager diff --name-only $diff_commits | grep '^src\|^tests\|^CMakeLists.txt\|^cmake\|^.github/workflows')
          echo "::set-output name=has_source_files::$([[ "$source_files" == "" ]] && echo 0 || echo 1)"

  build:
    name: build
    needs: lint
    if: ${{ needs.lint.outputs.has_source_files != 0 }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos7
          - ubuntu1804
        compiler:
          - gcc-9.2
          - clang-9
        exclude:
          - os: centos7
            compiler: clang-9
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
      env:
        TOOLSET_DIR: /opt/vesoft/toolset/clang/9.0.0
        CCACHE_DIR: /tmp/ccache/nebula-graph/${{ matrix.os }}-${{ matrix.compiler }}
        CCACHE_MAXSIZE: 1G
        PYPI_MIRROR: https://mirrors.aliyun.com/pypi/simple/
      volumes:
        - /tmp/ccache/nebula-graph/${{ matrix.os }}-${{ matrix.compiler }}:/tmp/ccache/nebula-graph/${{ matrix.os }}-${{ matrix.compiler }}
      options: --mount type=tmpfs,destination=/tmp/ccache/nebula-graph,tmpfs-size=1073741824 --cap-add=SYS_PTRACE
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Prepare environment
        id: prepare
        run: |
          [ -d build/ ] && rm -rf build/* || mkdir -p build
          pip3 install -U setuptools -i $PYPI_MIRROR
          pip3 install -r tests/requirements.txt -i $PYPI_MIRROR
      - name: Checkout common
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/nebula-common
          token: ${{ secrets.GITHUB_TOKEN }}
          path: modules/common
      - name: Checkout storage
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/nebula-storage
          token: ${{ secrets.GITHUB_TOKEN }}
          path: modules/storage
      - name: CMake
        run: |
          case ${{ matrix.compiler }} in
          gcc-*)
            case ${{ matrix.os }} in
            centos7)
              # build with Release type
              cmake \
                  -DCMAKE_CXX_COMPILER=$TOOLSET_DIR/bin/g++ \
                  -DCMAKE_C_COMPILER=$TOOLSET_DIR/bin/gcc \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DENABLE_TESTING=on \
                  -DENABLE_BUILD_STORAGE=on \
                  -B build
              ;;
            ubuntu1804)
              # build with Debug type
              cmake \
                  -DCMAKE_CXX_COMPILER=$TOOLSET_DIR/bin/g++ \
                  -DCMAKE_C_COMPILER=$TOOLSET_DIR/bin/gcc \
                  -DCMAKE_BUILD_TYPE=Debug \
                  -DENABLE_TESTING=on \
                  -DENABLE_BUILD_STORAGE=on \
                  -B build
              ;;
            esac
            ;;
          clang-*)
            # build with Sanitizer
            cmake \
                -DCMAKE_CXX_COMPILER=$TOOLSET_DIR/bin/clang++ \
                -DCMAKE_C_COMPILER=$TOOLSET_DIR/bin/clang \
                -DCMAKE_BUILD_TYPE=Debug \
                -DENABLE_ASAN=on \
                -DENABLE_TESTING=on \
                -DENABLE_BUILD_STORAGE=on \
                -B build
            ;;
          esac
      - name: Make graph
        run: cmake --build build/ -j $(nproc)
      - name: CTest
        env:
          ASAN_OPTIONS: fast_unwind_on_malloc=1
        run: ctest -j $(($(nproc)/2+1)) --timeout 400 --output-on-failure
        working-directory: build/
        timeout-minutes: 15
      - name: Pytest
        env:
          NEBULA_TEST_LOGS_DIR: ${{ github.workspace }}/build/results
        run: ./ci/test.sh test
        timeout-minutes: 25
      - name: Cleanup
        if: ${{ always() }}
        run: rm -rf build modules/common modules/storage
