name: release

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  package:
    name: package and upload release assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          - centos6
          - centos7
          - centos8
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: package
        run: ./package/package.sh
      - uses: ./.github/actions/tagname-action
        id: tag
      - name: Get package name
        id: pkg
        run: |
          echo "::set-output name=filepath::$(find build/cpack_output -type f \( -iname \*.deb -o -iname \*.rpm \))"
      - uses: ./.github/actions/upload-assets-action
        with:
          file-path: ${{ steps.pkg.outputs.filepath }}
          tag: ${{ steps.tag.outputs.tag  }}

  docker_build_graph:
    name: build graphd docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions/tagname-action
        id: tagname
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: vesoft/nebula-graphd:${{ steps.tagname.output.tag }}
          push: true

  docker_build_storage:
    name: build storaged/metad docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - metad
          - storaged
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/nebula-storage
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions/tagname-action
        id: tagname
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.${{ matrix.service }}
          tags: vesoft/nebula-${{ matrix.service }}:${{ steps.tagname.output.tag }}
          push: true
