name: release

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  package:
    name: package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          - centos6
          - centos7
          - centos8
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/tagname-action
        id: tag
      - name: package
        run: ./package/package.sh -b ${{ steps.tag.outputs.tag }}
      - name: Get package name
        id: pkg
        run: |
          filename=$(find build/cpack_output -type f \( -iname \*.deb -o -iname \*.rpm \))
          sha256sum $filename > $filename.$SHA_EXT
          echo "::set-output name=filepath::$filename"
          echo "::set-output name=shafilepath::$filename.$SHA_EXT"
      - uses: ./.github/actions/upload-assets-action
        with:
          file-path: ${{ steps.pkg.outputs.filepath }}
          tag: ${{ steps.tag.outputs.tag  }}
      - name: upload package to oss
        run: |
          ./ci/scripts/upload-oss.sh \
            OSS_ENDPOINT=${{ secrets.OSS_ENDPOINT }} \
            OSS_ID=${{ secrets.OSS_ID }} \
            OSS_SECRET=${{ secrets.OSS_SECRET }} \
            tag=${{ steps.tag.outputs.tag }} \
            filepath=${{ steps.pkg.outputs.filepath }}
          ./ci/scripts/upload-oss.sh \
            OSS_ENDPOINT=${{ secrets.OSS_ENDPOINT }} \
            OSS_ID=${{ secrets.OSS_ID }} \
            OSS_SECRET=${{ secrets.OSS_SECRET }} \
            tag=${{ steps.tag.outputs.tag }} \
            filepath=${{ steps.pkg.outputs.shafilepath }}

  docker_build_graph:
    name: docker-graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/tagname-action
        id: tagname
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: vesoft/nebula-graphd:${{ steps.tagname.outputs.tag }}
          push: true
          build-args: |
            BRANCH=${{ steps.tagname.outputs.tag }}

  docker_build_storage:
    name: docker-storage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - metad
          - storaged
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/tagname-action
        id: tagname
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/nebula-storage
          ref: ${{ steps.tagname.outputs.tag }}
          path: modules/nebula-storage
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: modules/nebula-storage
          file: ./modules/nebula-storage/docker/Dockerfile.${{ matrix.service }}
          tags: vesoft/nebula-${{ matrix.service }}:${{ steps.tagname.outputs.tag }}
          push: true
          build-args: |
            BRANCH=${{ steps.tagname.outputs.tag }}
