name: release

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  package:
    name: build package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          # - centos6
          - centos7
          - centos8
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/tagname-action
        id: tag
      - name: package
        run: ./package/package.sh -b ${{ steps.tag.outputs.tag }}
      - name: output some vars
        id: vars
        env:
          SHA_EXT: sha256sum.txt
        run: |
          tag=$(echo ${{ github.ref }} | rev | cut -d/ -f1 | rev)
          filename=$(find pkg-build/cpack_output -type f \( -iname \*.deb -o -iname \*.rpm \))
          sha256sum $filename > $filename.$SHA_EXT
          subdir=$(echo $tag |sed 's/^v//')
          echo "::set-output name=subdir::$subdir"
      - uses: ./.github/actions/upload-assets-action
        with:
          asset-path: pkg-build/cpack_output
          tag: ${{ steps.tag.outputs.tag }}
      - uses: ./.github/actions/upload-to-oss-action
        with:
          key-id: ${{ secrets.OSS_ID }}
          key-secret: ${{ secrets.OSS_SECRET }}
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          bucket: nebula-graph
          asset-path: pkg-build/cpack_output
          target-path: package/${{ steps.vars.outputs.subdir }}

  docker_build_graph:
    name: docker-graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/tagname-action
        id: tagname
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: vesoft/nebula-graphd:${{ steps.tagname.outputs.tag }}
          push: true
          build-args: |
            BRANCH=${{ steps.tagname.outputs.tag }}

  docker_build_storage:
    name: docker-storage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - metad
          - storaged
          - tools
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/tagname-action
        id: tagname
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/nebula-storage
          ref: ${{ steps.tagname.outputs.tag }}
          path: modules/nebula-storage
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: modules/nebula-storage
          file: ./modules/nebula-storage/docker/Dockerfile.${{ matrix.service }}
          tags: vesoft/nebula-${{ matrix.service }}:${{ steps.tagname.outputs.tag }}
          push: true
          build-args: |
            BRANCH=${{ steps.tagname.outputs.tag }}
